name = "recipes-hypersloth-io"
type = "webpack"
account_id = "1c787a4e7a6972171826b9c0bdd5a4ee"
workers_dev = false
route = "https://recipes.hypersloth.io/*"
zone_id = "f26899c9ac5bea9fcc538b11963ebe78"

[site]
bucket = "./public"
entry-point = "workers-site"
